### PR TITLE
Fixed Piece-Square Tables position evaluation

### PR DESCRIPTION
**Pull request by Varsius**
Reversed the rows of the Piece-Square Tables as explained [here](https://github.com/healeycodes/andoma/issues/12).
Also added a small testcast to verify the functionality.

### CODE REVIEW

**Comment by healeycodes** [comment]
Hi @Varsius!

This looks great.

Two things:

- Can you fix the two failing tests? I think it's because the move values changed and the tests need to be updated.
- Do you think another test is necessary to cover black's POV? i.e. if black responds to e2e4 with e7e5 then black's positional value should improve.

**Comment by Varsius** [comment]
Oh sorry, that is my bad.. I will be working on a fix soon. And adding another test is no problem.

**Comment by Varsius** [comment]
Tests should be fixed now.

**Comment by healeycodes** [comment]
Thanks for the PR! This closes #12

**Pull request merged**
